spring.application.name=jobportal
server.port=8080

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal
spring.datasource.username=postgres
spring.datasource.password=

# Hibernate and JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret={#secret_key#}
jwt.expirationMs=3600000
